### ISSUE TITLE
Deprecation Warnings in Ember 1.13.8

### ISSUE THREAD

**Issue by sarus** [fivetanley/ember-inflector-bower#1]
I just upgraded to Ember 1.13.8 and started getting deprecation warnings that I think are coming from this bower component:

```
DEPRECATION: Using Ember.Handlebars.makeBoundHelper is deprecated. Please refactor to using `Ember.Helper.helper`. [deprecation id: ember-htmlbars.handlebars-make-bound-helper]
        at Object.deprecatedMakeBoundHelper [as makeBoundHelper] (https://neontetra.breach/assets/vendor.js:17299:11)
        at Object.handlebarsHelper [as helper] (https://neontetra.breach/assets/vendor.js:17203:68)
        at https://neontetra.breach/assets/vendor.js:76622:22
        at https://neontetra.breach/assets/vendor.js:76751:4
```

I'm including this component in my `bower.json` but to be honest I'm not sure why it's there (I did not see it in the ember-cli bower.json blueprint) so I'm assuming an add-on installed it at some point.

Is this component something we should be using?  If I remove it from my bower.json then my ember project fails to build so I'm assuming something is still using it.

Thanks!

**Comment by sarus** [comment]
Okay I think the problem is with ember-cli-mirage based on this issue here:

https://github.com/samselikoff/ember-cli-mirage/issues/221

Will try to update mirage and see if I can get rid of this dependency.
